export const
  GET_GUEST = 'GET_GUEST',
  GET_GUEST_SUCCESS = 'GET_GUEST_SUCCESS',
  GET_GUEST_FAIL = 'GET_GUEST_FAIL',
  ADD_GUEST = 'ADD_GUEST',
  ADD_GUEST_SUCCESS = 'ADD_GUEST_SUCCESS',
  ADD_GUEST_FAIL = 'ADD_GUEST_FAIL',
  ADD_GUEST_TAG = 'ADD_GUEST_TAG',
  ADD_GUEST_TAG_SUCCESS = 'ADD_GUEST_TAG_SUCCESS',
  ADD_GUEST_TAG_FAIL = 'ADD_GUEST_TAG_FAIL',
  UPDATE_GUEST_TIMEOUT = 'UPDATE_GUEST_TIMEOUT',
  UPDATE_GUEST_TIMEOUT_SUCCESS = 'UPDATE_GUEST_TIMEOUT_SUCCESS',
  UPDATE_GUEST_TIMEOUT_FAIL = 'UPDATE_GUEST_TIMEOUT_FAIL';
